INSERT INTO Moves VALUES (	1	,	'Absorb'	,	6	,	'Special'	,	20	,	100	,	25	,	'User recovers half the HP inflicted on opponent.'	);
INSERT INTO Moves VALUES (	2	,	'Acid'	,	7	,	'Special'	,	40	,	100	,	30	,	'May lower opponent''s Special Defense.'	);
INSERT INTO Moves VALUES (	3	,	'Acid Armor'	,	7	,	'Status'	,	NULL	,	NULL	,	40	,	'Sharply raises user''s Defense.'	);
INSERT INTO Moves VALUES (	4	,	'Agility'	,	10	,	'Status'	,	NULL	,	NULL	,	30	,	'Sharply raises user''s Speed.'	);
INSERT INTO Moves VALUES (	5	,	'Amnesia'	,	10	,	'Status'	,	NULL	,	NULL	,	20	,	'Sharply raises user''s Special Defense.'	);
INSERT INTO Moves VALUES (	6	,	'Aurora Beam'	,	12	,	'Special'	,	65	,	100	,	20	,	'May lower opponent''s Attack.'	);
INSERT INTO Moves VALUES (	7	,	'Barrage'	,	1	,	'Physical'	,	15	,	85	,	20	,	'Hits 2-5 times in one turn.'	);
INSERT INTO Moves VALUES (	8	,	'Barrier'	,	10	,	'Status'	,	NULL	,	NULL	,	30	,	'Sharply raises user''s Defense.'	);
INSERT INTO Moves VALUES (	9	,	'Bide'	,	1	,	1	,	NULL	,	NULL	,	10	,	'User takes damage for two turns then strikes back double.'	);
INSERT INTO Moves VALUES (	10	,	'Bind'	,	1	,	'Physical'	,	15	,	85	,	20	,	'Traps opponent, damaging them for 4-5 turns.'	);
INSERT INTO Moves VALUES (	11	,	'Bite'	,	1	,	'Physical'	,	60	,	100	,	25	,	'May cause flinching.'	);
INSERT INTO Moves VALUES (	12	,	'Blizzard'	,	12	,	'Special'	,	120	,	70	,	5	,	'May freeze opponent.'	);
INSERT INTO Moves VALUES (	13	,	'Body Slam'	,	1	,	'Physical'	,	85	,	100	,	15	,	'May paralyze opponent.'	);
INSERT INTO Moves VALUES (	14	,	'Bone Club'	,	9	,	'Physical'	,	65	,	85	,	20	,	'May cause flinching.'	);
INSERT INTO Moves VALUES (	15	,	'Bonemerang'	,	9	,	'Physical'	,	50	,	90	,	10	,	'Hits twice in one turn.'	);
INSERT INTO Moves VALUES (	16	,	'Bubble'	,	4	,	'Special'	,	20	,	100	,	30	,	'May lower opponent''s Speed.'	);
INSERT INTO Moves VALUES (	17	,	'BubbleBeam'	,	4	,	'Special'	,	65	,	100	,	20	,	'May lower opponent''s Speed.'	);
INSERT INTO Moves VALUES (	18	,	'Clamp'	,	4	,	'Physical'	,	35	,	85	,	10	,	'Traps opponent, damaging them for 4-5 turns.'	);
INSERT INTO Moves VALUES (	19	,	'Comet Punch'	,	1	,	'Physical'	,	18	,	85	,	15	,	'Hits 2-5 times in one turn.'	);
INSERT INTO Moves VALUES (	20	,	'Confuse Ray'	,	15	,	'Status'	,	NULL	,	100	,	10	,	'Confuses opponent.'	);
INSERT INTO Moves VALUES (	21	,	'Confusion'	,	10	,	'Special'	,	50	,	100	,	25	,	'May confuse opponent.'	);
INSERT INTO Moves VALUES (	22	,	'Constrict'	,	1	,	'Physical'	,	10	,	100	,	35	,	'May lower opponent''s Speed by one stage.'	);
INSERT INTO Moves VALUES (	23	,	'Conversion'	,	1	,	'Status'	,	NULL	,	NULL	,	30	,	'Changes user''s type to a type of one of its own moves.'	);
INSERT INTO Moves VALUES (	24	,	'Counter'	,	3	,	'Physical'	,	NULL	,	100	,	20	,	'When hit by a Physical Attack, user strikes back with 2x power.'	);
INSERT INTO Moves VALUES (	25	,	'Crabhammer'	,	4	,	'Physical'	,	90	,	90	,	10	,	'High critical hit ratio.'	);
INSERT INTO Moves VALUES (	26	,	'Cut'	,	1	,	'Physical'	,	50	,	95	,	30	,	NULL	);
INSERT INTO Moves VALUES (	27	,	'Defense Curl'	,	1	,	'Status'	,	NULL	,	NULL	,	40	,	'Raises user''s Defense.'	);
INSERT INTO Moves VALUES (	28	,	'Dig'	,	9	,	'Physical'	,	80	,	100	,	10	,	'Digs underground on first turn, attacks on second. Can also escape from caves.'	);
INSERT INTO Moves VALUES (	29	,	'Disable'	,	1	,	'Status'	,	NULL	,	100	,	20	,	'Opponent can''t use its last attack for a few turns.'	);
INSERT INTO Moves VALUES (	30	,	'Dizzy Punch'	,	1	,	'Physical'	,	70	,	100	,	10	,	'May confuse opponent.'	);
INSERT INTO Moves VALUES (	31	,	'Double Kick'	,	3	,	'Physical'	,	30	,	100	,	30	,	'Hits twice in one turn.'	);
INSERT INTO Moves VALUES (	32	,	'Double Team'	,	1	,	'Status'	,	NULL	,	NULL	,	15	,	'Raises user''s Evasiveness.'	);
INSERT INTO Moves VALUES (	33	,	'Double-Edge'	,	1	,	'Physical'	,	120	,	100	,	15	,	'User receives recoil damage.'	);
INSERT INTO Moves VALUES (	34	,	'DoubleSlap'	,	1	,	'Physical'	,	15	,	85	,	10	,	'Hits 2-5 times in one turn.'	);
INSERT INTO Moves VALUES (	35	,	'Dragon Rage'	,	14	,	'Special'	,	NULL	,	100	,	10	,	'Always inflicts 40 HP.'	);
INSERT INTO Moves VALUES (	36	,	'Dream Eater'	,	10	,	'Special'	,	100	,	100	,	15	,	'User recovers half the HP inflicted on a sleeping opponent.'	);
INSERT INTO Moves VALUES (	37	,	'Drill Peck'	,	5	,	'Physical'	,	80	,	100	,	20	,	NULL	);
INSERT INTO Moves VALUES (	38	,	'Earthquake'	,	9	,	'Physical'	,	100	,	100	,	10	,	'Power is doubled if opponent is underground from using Dig.'	);
INSERT INTO Moves VALUES (	39	,	'Egg Bomb'	,	1	,	'Physical'	,	100	,	75	,	10	,	NULL	);
INSERT INTO Moves VALUES (	40	,	'Ember'	,	2	,	'Special'	,	40	,	100	,	25	,	'May burn opponent.'	);
INSERT INTO Moves VALUES (	41	,	'Explosion'	,	1	,	'Physical'	,	250	,	100	,	5	,	'User faints.'	);
INSERT INTO Moves VALUES (	42	,	'Fire Blast'	,	2	,	'Special'	,	120	,	85	,	5	,	'May burn opponent.'	);
INSERT INTO Moves VALUES (	43	,	'Fire Punch'	,	2	,	'Physical'	,	75	,	100	,	15	,	'May burn opponent.'	);
INSERT INTO Moves VALUES (	44	,	'Fire Spin'	,	2	,	'Special'	,	35	,	85	,	15	,	'Traps opponent, damaging them for 4-5 turns.'	);
INSERT INTO Moves VALUES (	45	,	'Fissure'	,	9	,	'Physical'	,	NULL	,	NULL	,	5	,	'One-Hit-KO, if it hits.'	);
INSERT INTO Moves VALUES (	46	,	'Flamethrower'	,	2	,	'Special'	,	95	,	100	,	15	,	'May burn opponent.'	);
INSERT INTO Moves VALUES (	47	,	'Flash'	,	1	,	'Status'	,	NULL	,	100	,	20	,	'Lowers opponent''s Accuracy.'	);
INSERT INTO Moves VALUES (	48	,	'Fly'	,	5	,	'Physical'	,	90	,	95	,	15	,	'Flies up on first turn, attacks on second turn.'	);
INSERT INTO Moves VALUES (	49	,	'Focus Energy'	,	1	,	'Status'	,	NULL	,	NULL	,	30	,	'Increases critical hit ratio.'	);
INSERT INTO Moves VALUES (	50	,	'Fury Attack'	,	1	,	'Physical'	,	15	,	85	,	20	,	'Hits 2-5 times in one turn.'	);
INSERT INTO Moves VALUES (	51	,	'Fury Swipes'	,	1	,	'Physical'	,	18	,	80	,	15	,	'Hits 2-5 times in one turn.'	);
INSERT INTO Moves VALUES (	52	,	'Glare'	,	1	,	'Status'	,	NULL	,	90	,	30	,	'Paralyzes opponent.'	);
INSERT INTO Moves VALUES (	53	,	'Growl'	,	1	,	'Status'	,	NULL	,	100	,	40	,	'Lowers opponent''s Attack.'	);
INSERT INTO Moves VALUES (	54	,	'Growth'	,	1	,	'Status'	,	NULL	,	NULL	,	40	,	'Raises user''s Attack and Special Attack.'	);
INSERT INTO Moves VALUES (	55	,	'Guillotine'	,	1	,	'Physical'	,	NULL	,	NULL	,	5	,	'One-Hit-KO, if it hits.'	);
INSERT INTO Moves VALUES (	56	,	'Gust'	,	5	,	'Special'	,	40	,	100	,	35	,	'Hits Pokemon using Fly/Bounce with double power.'	);
INSERT INTO Moves VALUES (	57	,	'Harden'	,	1	,	'Status'	,	NULL	,	NULL	,	30	,	'Raises user''s Defense.'	);
INSERT INTO Moves VALUES (	58	,	'Haze'	,	12	,	'Status'	,	NULL	,	NULL	,	30	,	'Resets all stat changes.'	);
INSERT INTO Moves VALUES (	59	,	'Headbutt'	,	1	,	'Physical'	,	70	,	100	,	15	,	'May cause flinching.'	);
INSERT INTO Moves VALUES (	60	,	'Hi Jump Kick'	,	3	,	'Physical'	,	130	,	90	,	10	,	'If it misses, the user loses half their HP.'	);
INSERT INTO Moves VALUES (	61	,	'Horn Attack'	,	1	,	'Physical'	,	65	,	100	,	25	,	NULL	);
INSERT INTO Moves VALUES (	62	,	'Horn Drill'	,	1	,	'Physical'	,	NULL	,	NULL	,	5	,	'One-Hit-KO, if it hits.'	);
INSERT INTO Moves VALUES (	63	,	'Hydro Pump'	,	4	,	'Special'	,	120	,	80	,	5	,	NULL	);
INSERT INTO Moves VALUES (	64	,	'Hyper Beam'	,	1	,	'Special'	,	150	,	90	,	5	,	'User must recharge next turn.'	);
INSERT INTO Moves VALUES (	65	,	'Hyper Fang'	,	1	,	'Physical'	,	80	,	90	,	15	,	'May cause flinching.'	);
INSERT INTO Moves VALUES (	66	,	'Hypnosis'	,	10	,	'Status'	,	NULL	,	60	,	20	,	'Put opponent to sleep, if it hits.'	);
INSERT INTO Moves VALUES (	67	,	'Ice Beam'	,	12	,	'Special'	,	95	,	100	,	10	,	'May freeze opponent.'	);
INSERT INTO Moves VALUES (	68	,	'Ice Punch'	,	12	,	'Physical'	,	75	,	100	,	15	,	'May freeze opponent.'	);
INSERT INTO Moves VALUES (	69	,	'Jump Kick'	,	3	,	'Physical'	,	100	,	95	,	10	,	'If it misses, the user loses half their HP.'	);
INSERT INTO Moves VALUES (	70	,	'Karate Chop'	,	3	,	'Physical'	,	50	,	100	,	25	,	'High critical hit ratio.'	);
INSERT INTO Moves VALUES (	71	,	'Kinesis'	,	10	,	'Status'	,	NULL	,	80	,	15	,	'Lowers opponent''s Accuracy.'	);
INSERT INTO Moves VALUES (	72	,	'Leech Life'	,	13	,	'Physical'	,	20	,	100	,	15	,	'User recovers half the HP inflicted on opponent.'	);
INSERT INTO Moves VALUES (	73	,	'Leech Seed'	,	6	,	'Status'	,	NULL	,	90	,	10	,	'User steals HP from opponent each turn.'	);
INSERT INTO Moves VALUES (	74	,	'Leer'	,	1	,	'Status'	,	NULL	,	100	,	30	,	'Lowers opponent''s Defense.'	);
INSERT INTO Moves VALUES (	75	,	'Lick'	,	15	,	'Physical'	,	20	,	100	,	30	,	'May paralyze opponent.'	);
INSERT INTO Moves VALUES (	76	,	'Light Screen'	,	10	,	'Status'	,	NULL	,	NULL	,	30	,	'Halves damage from special attacks for 5 turns.'	);
INSERT INTO Moves VALUES (	77	,	'Lovely Kiss'	,	1	,	'Status'	,	NULL	,	75	,	10	,	'Puts the opponent to sleep, if it hits.'	);
INSERT INTO Moves VALUES (	78	,	'Low Kick'	,	3	,	'Physical'	,	NULL	,	100	,	20	,	'The heavier the opponent, the stronger the attack.'	);
INSERT INTO Moves VALUES (	79	,	'Meditate'	,	10	,	'Status'	,	NULL	,	NULL	,	40	,	'Raises user''s Attack.'	);
INSERT INTO Moves VALUES (	80	,	'Mega Drain'	,	6	,	'Special'	,	40	,	100	,	15	,	'User recovers half the HP inflicted on opponent.'	);
INSERT INTO Moves VALUES (	81	,	'Mega Kick'	,	1	,	'Physical'	,	120	,	75	,	5	,	NULL	);
INSERT INTO Moves VALUES (	82	,	'Mega Punch'	,	1	,	'Physical'	,	80	,	85	,	20	,	NULL	);
INSERT INTO Moves VALUES (	83	,	'Metronome'	,	1	,	'Status'	,	NULL	,	NULL	,	10	,	'User performs any move in the game at random.'	);
INSERT INTO Moves VALUES (	84	,	'Mimic'	,	1	,	'Status'	,	NULL	,	NULL	,	10	,	'Copies the opponent''s last move.'	);
INSERT INTO Moves VALUES (	85	,	'Minimize'	,	1	,	'Status'	,	NULL	,	NULL	,	20	,	'Sharply raises user''s Evasiveness.'	);
INSERT INTO Moves VALUES (	86	,	'Mirror Move'	,	5	,	'Status'	,	NULL	,	NULL	,	20	,	'User performs the opponent''s last move.'	);
INSERT INTO Moves VALUES (	87	,	'Mist'	,	12	,	'Status'	,	NULL	,	NULL	,	30	,	'User''s stats cannot be changed for a period of time.'	);
INSERT INTO Moves VALUES (	88	,	'Night Shade'	,	15	,	'Special'	,	NULL	,	100	,	15	,	'Inflicts damage equal to user''s level.'	);
INSERT INTO Moves VALUES (	89	,	'Pay Day'	,	1	,	'Physical'	,	40	,	100	,	20	,	'A small amount of money is gained after the battle resolves.'	);
INSERT INTO Moves VALUES (	90	,	'Peck'	,	5	,	'Physical'	,	35	,	100	,	35	,	NULL	);
INSERT INTO Moves VALUES (	91	,	'Petal Dance'	,	6	,	'Special'	,	120	,	100	,	10	,	'User attacks for 2-3 turns but then becomes confused.'	);
INSERT INTO Moves VALUES (	92	,	'Pin Missile'	,	13	,	'Physical'	,	14	,	85	,	20	,	'Hits 2-5 times in one turn.'	);
INSERT INTO Moves VALUES (	93	,	'Poison Gas'	,	7	,	'Status'	,	NULL	,	85	,	40	,	'Poisons opponent.'	);
INSERT INTO Moves VALUES (	94	,	'Poison Sting'	,	7	,	'Physical'	,	15	,	100	,	35	,	'May poison the opponent.'	);
INSERT INTO Moves VALUES (	95	,	'PoisonPowder'	,	7	,	'Status'	,	NULL	,	75	,	35	,	'Poisons opponent.'	);
INSERT INTO Moves VALUES (	96	,	'Pound'	,	1	,	'Physical'	,	40	,	100	,	35	,	NULL	);
INSERT INTO Moves VALUES (	97	,	'Psybeam'	,	10	,	'Special'	,	65	,	100	,	20	,	'May confuse opponent.'	);
INSERT INTO Moves VALUES (	98	,	'Psychic'	,	10	,	'Special'	,	90	,	100	,	10	,	'May lower opponent''s Special Defense.'	);
INSERT INTO Moves VALUES (	99	,	'Psywave'	,	10	,	'Special'	,	NULL	,	80	,	15	,	'Inflicts damage 50-150% of user''s level.'	);
INSERT INTO Moves VALUES (	100	,	'Quick Attack'	,	1	,	'Physical'	,	40	,	100	,	30	,	'User attacks first.'	);
INSERT INTO Moves VALUES (	101	,	'Rage'	,	1	,	'Physical'	,	20	,	100	,	20	,	'Raises user''s Attack when hit.'	);
INSERT INTO Moves VALUES (	102	,	'Razor Leaf'	,	6	,	'Physical'	,	55	,	95	,	25	,	'High critical hit ratio.'	);
INSERT INTO Moves VALUES (	103	,	'Razor Wind'	,	1	,	'Special'	,	80	,	100	,	10	,	'Charges on first turn, attacks on second. High critical hit ratio.'	);
INSERT INTO Moves VALUES (	104	,	'Recover'	,	1	,	'Status'	,	NULL	,	NULL	,	10	,	'User recovers 50% of its max HP.'	);
INSERT INTO Moves VALUES (	105	,	'Reflect'	,	10	,	'Status'	,	NULL	,	NULL	,	20	,	'Halves damage from physical attacks for 5 turns.'	);
INSERT INTO Moves VALUES (	106	,	'Rest'	,	10	,	'Status'	,	NULL	,	NULL	,	10	,	'User sleeps for 2 turns, but user is fully healed.'	);
INSERT INTO Moves VALUES (	107	,	'Roar'	,	1	,	'Status'	,	NULL	,	100	,	20	,	'In battles, the opponent switches. In the wild, the Pokemon runs.'	);
INSERT INTO Moves VALUES (	108	,	'Rock Slide'	,	11	,	'Physical'	,	75	,	90	,	10	,	'May cause flinching.'	);
INSERT INTO Moves VALUES (	109	,	'Rock Throw'	,	11	,	'Physical'	,	50	,	90	,	15	,	NULL	);
INSERT INTO Moves VALUES (	110	,	'Rolling Kick'	,	3	,	'Physical'	,	60	,	85	,	15	,	'May cause flinching.'	);
INSERT INTO Moves VALUES (	111	,	'Sand-Attack'	,	9	,	'Status'	,	NULL	,	100	,	15	,	'Lowers opponent''s Accuracy.'	);
INSERT INTO Moves VALUES (	112	,	'Scratch'	,	1	,	'Physical'	,	40	,	100	,	35	,	NULL	);
INSERT INTO Moves VALUES (	113	,	'Screech'	,	1	,	'Status'	,	NULL	,	85	,	40	,	'Sharply lowers opponent''s Defense.'	);
INSERT INTO Moves VALUES (	114	,	'Seismic Toss'	,	3	,	'Physical'	,	NULL	,	100	,	20	,	'Inflicts damage equal to user''s level.'	);
INSERT INTO Moves VALUES (	115	,	'Selfdestruct'	,	1	,	'Physical'	,	200	,	100	,	5	,	'User faints.'	);
INSERT INTO Moves VALUES (	116	,	'Sharpen'	,	1	,	'Status'	,	NULL	,	NULL	,	30	,	'Raises user''s Attack.'	);
INSERT INTO Moves VALUES (	117	,	'Sing'	,	1	,	'Status'	,	NULL	,	55	,	15	,	'Puts the opponent to sleep, if it hits.'	);
INSERT INTO Moves VALUES (	118	,	'Skull Bash'	,	1	,	'Physical'	,	100	,	100	,	15	,	'Raises Defense on first turn, attacks on second.'	);
INSERT INTO Moves VALUES (	119	,	'Sky Attack'	,	5	,	'Physical'	,	140	,	90	,	5	,	'Charges on first turn, attacks on second. May cause flinching.'	);
INSERT INTO Moves VALUES (	120	,	'Slam'	,	1	,	'Physical'	,	80	,	75	,	20	,	NULL	);
INSERT INTO Moves VALUES (	121	,	'Slash'	,	1	,	'Physical'	,	70	,	100	,	20	,	'High critical hit ratio.'	);
INSERT INTO Moves VALUES (	122	,	'Sleep Powder'	,	6	,	'Status'	,	NULL	,	75	,	15	,	'Puts the opponent to sleep, if it hits.'	);
INSERT INTO Moves VALUES (	123	,	'Sludge'	,	7	,	'Special'	,	65	,	100	,	20	,	'May poison opponent.'	);
INSERT INTO Moves VALUES (	124	,	'Smog'	,	7	,	'Special'	,	20	,	70	,	20	,	'May poison opponent.'	);
INSERT INTO Moves VALUES (	125	,	'SmokeScreen'	,	1	,	'Status'	,	NULL	,	100	,	20	,	'Lowers opponent''s Accuracy.'	);
INSERT INTO Moves VALUES (	126	,	'Softboiled'	,	1	,	'Status'	,	NULL	,	NULL	,	10	,	'User recovers 50% of its max HP.'	);
INSERT INTO Moves VALUES (	127	,	'SolarBeam'	,	6	,	'Special'	,	120	,	100	,	10	,	'Charges on first turn, attacks on second.'	);
INSERT INTO Moves VALUES (	128	,	'SonicBoom'	,	1	,	'Special'	,	NULL	,	90	,	20	,	'Always inflicts 20 HP.'	);
INSERT INTO Moves VALUES (	129	,	'Spike Cannon'	,	1	,	'Physical'	,	20	,	100	,	15	,	'Hits 2-5 times in one turn.'	);
INSERT INTO Moves VALUES (	130	,	'Splash'	,	1	,	'Status'	,	NULL	,	NULL	,	40	,	'Doesn''t do ANYTHING.'	);
INSERT INTO Moves VALUES (	131	,	'Spore'	,	6	,	'Status'	,	NULL	,	100	,	15	,	'Puts the opponent to sleep.'	);
INSERT INTO Moves VALUES (	132	,	'Stomp'	,	1	,	'Physical'	,	65	,	100	,	20	,	'May cause flinching.'	);
INSERT INTO Moves VALUES (	133	,	'Strength'	,	1	,	'Physical'	,	80	,	100	,	15	,	NULL	);
INSERT INTO Moves VALUES (	134	,	'String Shot'	,	13	,	'Status'	,	NULL	,	95	,	40	,	'Lowers opponent''s Speed.'	);
INSERT INTO Moves VALUES (	135	,	'Struggle'	,	1	,	'Physical'	,	50	,	100	,	NULL	,	'Only usable when all PP are gone. Hurts the user.'	);
INSERT INTO Moves VALUES (	136	,	'Stun Spore'	,	6	,	'Status'	,	NULL	,	75	,	30	,	'Paralyzes opponent.'	);
INSERT INTO Moves VALUES (	137	,	'Submission'	,	3	,	'Physical'	,	80	,	80	,	25	,	'User receives recoil damage.'	);
INSERT INTO Moves VALUES (	138	,	'Substitute'	,	1	,	'Status'	,	NULL	,	NULL	,	10	,	'Uses HP to creates a decoy that takes hits.'	);
INSERT INTO Moves VALUES (	139	,	'Super Fang'	,	1	,	'Physical'	,	NULL	,	90	,	10	,	'Always takes off half of the opponent''s HP.'	);
INSERT INTO Moves VALUES (	140	,	'Supersonic'	,	1	,	'Status'	,	NULL	,	55	,	20	,	'Confuses opponent.'	);
INSERT INTO Moves VALUES (	141	,	'Surf'	,	4	,	'Special'	,	95	,	100	,	15	,	NULL	);
INSERT INTO Moves VALUES (	142	,	'Swift'	,	1	,	'Special'	,	60	,	NULL	,	20	,	'Ignores Accuracy and Evasiveness.'	);
INSERT INTO Moves VALUES (	143	,	'Swords Dance'	,	1	,	'Status'	,	NULL	,	NULL	,	30	,	'Sharply raises user''s Attack.'	);
INSERT INTO Moves VALUES (	144	,	'Tackle'	,	1	,	'Physical'	,	50	,	100	,	35	,	NULL	);
INSERT INTO Moves VALUES (	145	,	'Tail Whip'	,	1	,	'Status'	,	NULL	,	100	,	30	,	'Lowers opponent''s Defense.'	);
INSERT INTO Moves VALUES (	146	,	'Take Down'	,	1	,	'Physical'	,	90	,	85	,	20	,	'User receives recoil damage.'	);
INSERT INTO Moves VALUES (	147	,	'Teleport'	,	10	,	'Status'	,	NULL	,	NULL	,	20	,	'Allows user to switch out. In the wild, the battle ends.'	);
INSERT INTO Moves VALUES (	148	,	'Thrash'	,	1	,	'Physical'	,	120	,	100	,	10	,	'User attacks for 2-3 turns but then becomes confused.'	);
INSERT INTO Moves VALUES (	149	,	'Thunder'	,	8	,	'Special'	,	120	,	70	,	10	,	'May paralyze opponent.'	);
INSERT INTO Moves VALUES (	150	,	'Thunder Wave'	,	8	,	'Status'	,	NULL	,	100	,	20	,	'Paralyzes opponent.'	);
INSERT INTO Moves VALUES (	151	,	'ThunderPunch'	,	8	,	'Physical'	,	75	,	100	,	15	,	'May paralyze opponent.'	);
INSERT INTO Moves VALUES (	152	,	'ThunderShock'	,	8	,	'Special'	,	40	,	100	,	30	,	'May paralyze opponent.'	);
INSERT INTO Moves VALUES (	153	,	'Thunderbolt'	,	8	,	'Special'	,	95	,	100	,	15	,	'May paralyze opponent.'	);
INSERT INTO Moves VALUES (	154	,	'Toxic'	,	7	,	'Status'	,	NULL	,	90	,	10	,	'Badly poisons opponent.'	);
INSERT INTO Moves VALUES (	155	,	'Transform'	,	1	,	'Status'	,	NULL	,	NULL	,	10	,	'User takes on the form and attacks of the opponent.'	);
INSERT INTO Moves VALUES (	156	,	'Tri Attack'	,	1	,	'Special'	,	80	,	100	,	10	,	'May paralyze, burn or freeze opponent.'	);
INSERT INTO Moves VALUES (	157	,	'Twineedle'	,	13	,	'Physical'	,	25	,	100	,	20	,	'Hits twice in one turn. May poison opponent.'	);
INSERT INTO Moves VALUES (	158	,	'ViceGrip'	,	1	,	'Physical'	,	55	,	100	,	30	,	NULL	);
INSERT INTO Moves VALUES (	159	,	'Vine Whip'	,	6	,	'Physical'	,	35	,	100	,	15	,	NULL	);
INSERT INTO Moves VALUES (	160	,	'Water Gun'	,	4	,	'Special'	,	40	,	100	,	25	,	NULL	);
INSERT INTO Moves VALUES (	161	,	'Waterfall'	,	4	,	'Physical'	,	80	,	100	,	15	,	'May cause flinching.'	);
INSERT INTO Moves VALUES (	162	,	'Whirlwind'	,	1	,	'Status'	,	NULL	,	100	,	20	,	'In battles, the opponent switches. In the wild, the Pokemon runs.'	);
INSERT INTO Moves VALUES (	163	,	'Wing Attack'	,	5	,	'Physical'	,	60	,	100	,	35	,	NULL	);
INSERT INTO Moves VALUES (	164	,	'Withdraw'	,	4	,	'Status'	,	NULL	,	NULL	,	40	,	'Raises user''s Defense.'	);
INSERT INTO Moves VALUES (	165	,	'Wrap'	,	1	,	'Physical'	,	15	,	90	,	20	,	'Traps opponent, damaging them for 4-5 turns.'	);
COMMIT;